GET http://localhost:1200

### all users
GET http://localhost:1200/users

### login with username
POST http://localhost:1200/login
Content-Type: application/json

{
    "username": "John Doe"
}

### get user by username
GET http://localhost:1200/users/John%20Doe

### get user by id

### create user
POST http://localhost:1200/users
Content-Type: application/json

{
    "username": "Wwe Doe"
}

### get all tasks
GET http://localhost:1200/tasks

### create task
POST http://localhost:1200/tasks
Content-Type: application/json

{
    "title": "Task 1",
    "description": "Description 1",
    "user": 2
}

### delete task
DELETE http://localhost:1200/tasks/2


### update task status
PUT http://localhost:1200/tasks/3/status
Content-Type: application/json

{
    "status": "Done",
    "user": 2
}


### reassign task
PUT http://localhost:1200/tasks/2/assign
Content-Type: application/json

{
    "user": 2,
    "newUser": 2
}

### get changes history
GET http://localhost:1200/tasks/3/history
