GET http://localhost:1200

###
GET http://localhost:1200/users

###
POST http://localhost:1200/users
Content-Type: application/json

{
    "username": "Wwe Doe"
}

###
GET http://localhost:1200/tasks

###
POST http://localhost:1200/tasks
Content-Type: application/json

{
    "title": "Task 1",
    "description": "Description 1",
    "user": 2
}

### update task status
PUT http://localhost:1200/tasks/3/status
Content-Type: application/json

{
    "status": "Blocked",
    "user": 2
}


### reassign task
PUT http://localhost:1200/tasks/2/assign
Content-Type: application/json

{
    "user": 2,
    "newUser": 3
}